# Generated by Django 5.0.6 on 2024-06-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='pdf',
            field=models.FileField(default=1, upload_to=True),
            preserve_default=False,
        ),
    ]
