# Generated by Django 5.0.6 on 2024-06-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_desc_news_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
