# Generated by Django 5.0.6 on 2024-06-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
